[tool.poetry]
name = "form-catch"
version = "0.1.0"
description = "API to catch form submissions from a website"
authors = ["Grant Ramsay <seapagan@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.0"
ormar = { extras = ["postgresql"], version = "^0.12.1" }
uvicorn = { extras = ["standard"], version = "^0.21.1" }
alembic = "^1.10.3"
python-decouple = "^3.8"
python-multipart = "^0.0.6"
fastapi-mail = {extras = ["httpx"], version = "^1.2.7"}


[tool.poetry.group.dev.dependencies]
pydocstyle = "^6.3.0"
flake8-docstrings = "^1.7.0"
flake8 = "^6.0.0"
black = "^23.3.0"
pylint = "^2.17.2"
pep8-naming = "^0.13.3"
openapi-readme = "^0.2.1"
bandit = "^1.7.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
