"""add redirect_url field to database

Revision ID: 0a8f61e10feb
Revises: ba9b92915cfa
Create Date: 2023-04-10 10:28:38.115256

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a8f61e10feb"
down_revision = "ba9b92915cfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sites", sa.Column("redirect_url", sa.String(length=100), nullable=True)
    )
    op.create_unique_constraint(None, "sites", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sites", type_="unique")
    op.drop_column("sites", "redirect_url")
    # ### end Alembic commands ###
