"""add Users and Auth

Revision ID: 290573eb9d06
Revises: e77860c4b84e
Create Date: 2023-04-30 17:57:15.860233

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "290573eb9d06"
down_revision = "e77860c4b84e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=30), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="roletype"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("banned", sa.Boolean(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
