"""link users to sites table

Revision ID: 9ae35235b8c8
Revises: 290573eb9d06
Create Date: 2023-04-30 19:58:59.143091

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ae35235b8c8"
down_revision = "290573eb9d06"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "sites", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sites", type_="foreignkey")
    op.drop_column("sites", "user_id")
    # ### end Alembic commands ###
