"""add email to sites model

Revision ID: ba9b92915cfa
Revises: 7c76210d2b84
Create Date: 2023-03-31 17:55:26.104821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9b92915cfa'
down_revision = '7c76210d2b84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('email', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'email')
    # ### end Alembic commands ###
